################
# server
################
server.port: 8080
spring:
   devtools:
      restart.exclude: static/**,public/**,templates/**
      livereload.enabled: true
   thymeleaf:
      cache: false
      mode: LEGACYHTML5
   template:
      cache: false
   datasource:
      url: 'jdbc:mysql://10.16.238.83:3306/AutoProgramming?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true'
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

